LIBDRM_AMDGPU_FILES := \
	amdgpu_bo.c \
	amdgpu_cs.c \
	amdgpu_device.c \
	amdgpu_gpu_info.c \
	amdgpu_vamgr.c \
	util_hash.c \
	util_hash_table.c

LIBDRM_AMDGPU_H_FILES := \
	amdgpu.h \
	amdgpu_internal.h \
	util_hash.h \
	util_hash_table.h
